version: "3.5"

services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
     # 初始化数据库
     # MYSQL_DATABASE: task_admin
    networks:
      - jiny_bridge

  redis:
    image: redis:6.0.6
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass xapp
    environment:
      - TZ=Asia/Shanghai
    networks:
      - jiny_bridge

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/web:/etc/nginx/web
    networks:
      - jiny_bridge
      
  influxdb:
    image: influxdb:1.5.4
    container_name: influxdb
    volumes:
      - ./influxdb/data/data:/var/lib/influxdb/data
      - ./influxdb/data/meta:/var/lib/influxdb/meta
      - ./influxdb/data/wal:/var/lib/influxdb/wal
    ports:
      - 8083:8083
      - 28086:8086
      - 8089:8089/udp
    restart: always
    networks:
      - jiny_bridge

  nacos:
    image: nacos/nacos-server:1.3.2
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=127.0.0.1
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=123456
    volumes:
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
    restart: always
    depends_on:
      - mysql
    networks:
      - jiny_bridge

  taos:
    image: tdengine/tdengine:3.0.1.6
    hostname: taos-server
    container_name: taos
    ports:
      - 6030-6049:6030-6049
      - 6030-6049:6030-6049/udp
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./taos/data:/var/lib/taos/
      - ./taos/log:/var/log/taos/
    networks:
      - jiny_bridge

  emqx:
    image: emqx/emqx:v4.1.4
    container_name: emqx
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
    networks:
      - jiny_bridge

networks:
  jiny_bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
       
