version: "3"

services:
#  nginx:
#    image: nginx:1.18.0
#    restart: always
#    container_name: nginx
#    ports:
#      - 80:80
#    depends_on:
#      - go
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./web/:/etc/nginx/web
#    networks:
#      - iotnet

  taos:
    image: tdengine/tdengine:2.6.0.6
    hostname: taos-server
    container_name: taos
    ports:
      - 6030-6049:6030-6049
      - 6030-6049:6030-6049/udp
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - taosdata:/var/lib/taos/
      - taoslog:/var/log/taos/
    networks:
      - iotnet

  go:
    build: .
    image: iot:1.0
    container_name: go
    restart: always
    depends_on:
      - taos
    ports:
      - 8080:8080
    networks:
      - iotnet

volumes:
  taosdata:
  taoslog:


networks:
  iotnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24