version: "3"

services:
#  nginx:
#    image: nginx:1.18.0
#    restart: always
#    container_name: nginx
#    ports:
#      - 80:80
#    depends_on:
#      - go
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./web/:/etc/nginx/web
#    networks:
#      - hjnet

  taos:
    image: tdengine/tdengine:3.0.1.6
    hostname: taos-server
    container_name: taos
    ports:
      - 6030-6049:6030-6049
      - 6030-6049:6030-6049/udp
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - taosdata:/var/lib/taos/
      - taoslog:/var/log/taos/
    networks:
      - hjnet

  hjaccess:
    build: ./hjdemo-access
    image: hjaccess:4.0
    container_name: hjaccess
    restart: always
    depends_on:
      - taos
      - emqx
    ports:
      - 8888:8888
    networks:
      - hjnet

  hjweb:
    build: ./hjdemo-web
    image: hjweb:4.0
    container_name: hjweb
    restart: always
    depends_on:
      - taos
      - emqx
#    ports:
#      - 8888:8888
    networks:
      - hjnet

  emqx:
    image: emqx/emqx:v4.1.4
    container_name: emqx
#    restart: unless-stopped
    ports: # web页面端口
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
    networks:
      - hjnet

volumes:
  taosdata:
  taoslog:


networks:
  hjnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24